version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: etl_bench_postgres
    environment:
      POSTGRES_USER: etl
      POSTGRES_PASSWORD: etl
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    volumes:
      - ./data/services/postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-01-11T07-46-16Z
    container_name: etl_bench_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/services/minio:/data
